{
 "title": "Solana Monitoring Dashboard by AiNodes",
 "description": "Validator statistics run by AiNodes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pubkey",
    "label": "Pubkey",
    "query": {
     "query": "label_values(nodemonitor_status,pubkey)"
    }
   },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   { "name": "job", "query": "node-exporter" },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(nodemonitor_status{pubkey=\"$pubkey\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick stats $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "# Solana Monitoring Dashboard\n*check out our [github repo](https://github.com/AiNodes-Tech/solana-monitoring) if you want to start pushing metrics."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Epoch Ends In",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nodemonitor_epochEnds{pubkey=\"$pubkey\", instance=\"$node\"} / 1000 - time()",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Epoch% Progress",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodemonitor_pctEpochElapsed{pubkey=\"$pubkey\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoch Ends",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nodemonitor_epochEnds{pubkey=\"$pubkey\", instance=\"$node\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nodemonitor_status{pubkey=\"$pubkey\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leaderslots this epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodemonitor_leaderSlots{pubkey=\"$pubkey\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missed Slots",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodemonitor_skippedSlots{pubkey=\"$pubkey\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skiprate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodemonitor_pctSkipped{pubkey=\"$pubkey\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Stake",
   "type": "stat",
   "description": "Active stake on the validator.",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodemonitor_activatedStake{pubkey=\"$pubkey\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodemonitor_nodes{pubkey=\"$pubkey\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes pushing metrics",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(nodemonitor_nodes)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Balance",
   "type": "stat",
   "description": "Active stake on the validator.",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodemonitor_validatorBalance{pubkey=\"$pubkey\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balance for",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(nodemonitor_validatorBalance{pubkey=\"$pubkey\", instance=\"$node\"} / 0.000005) * 0.4",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Voting rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodemonitor_pctVote{pubkey=\"$pubkey\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/ usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/solana usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/data\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/data\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ramdisk usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=~\".*ramdisk.*\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=~\".*ramdisk.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load5{instance=\"$node\",job=\"$job\"}) / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SOL/USDT",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodemonitor_solanaPrice{pubkey=\"$pubkey\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Fee",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodemonitor_commission{pubkey=\"$pubkey\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodemonitor_epoch{pubkey=\"$pubkey\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solana Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodemonitor_version{pubkey=\"$pubkey\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Validator Stats $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "node" },
  {
   "title": "My Skiprate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nodemonitor_pctSkipped{pubkey=\"$pubkey\"}",
     "legendFormat": "My Skiprate"
    },
    {
     "expr": "nodemonitor_pctTotSkipped{pubkey=\"$pubkey\"}",
     "legendFormat": "Cluster Skiprate"
    }
   ]
  },
  {
   "title": "Cluster TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "targets": [
    {
     "expr": "rate(nodemonitor_tps{pubkey=\"$pubkey\"}[1m])",
     "legendFormat": "Cluster TPS"
    }
   ]
  },
  {
   "title": "My Leaderslots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nodemonitor_leaderSlots{pubkey=\"$pubkey\"}",
     "legendFormat": "Leaderslots"
    },
    {
     "expr": "nodemonitor_skippedSlots{pubkey=\"$pubkey\"}",
     "legendFormat": "Skipped"
    }
   ]
  },
  {
   "title": "My Credits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(nodemonitor_credits{pubkey=\"$pubkey\"}[1m])",
     "legendFormat": "Credits $server"
    }
   ]
  },
  {
   "title": "Vote Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodemonitor_pctVote{pubkey=\"$pubkey\"}",
     "legendFormat": "vote %"
    }
   ]
  },
  {
   "title": "Credits Current Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nodemonitor_validatorCreditsCurrent{pubkey=\"$pubkey\"}",
     "legendFormat": "Validator Credits $server"
    }
   ]
  },
  {
   "title": "% Total Network Delinquency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nodemonitor_pctTotDelinquent{pubkey=\"$pubkey\"}",
     "legendFormat": "Total % Cluster Delinquency"
    }
   ]
  },
  {
   "title": "Balance on Identity Acccount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "targets": [
    {
     "expr": "nodemonitor_validatorBalance{pubkey=\"$pubkey\"}",
     "legendFormat": "Balance $pubkey"
    }
   ]
  },
  {
   "title": "Active Stake",
   "type": "timeseries",
   "description": "Active stake on the validator.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "targets": [
    {
     "expr": "nodemonitor_activatedStake{pubkey=\"$pubkey\"}",
     "legendFormat": "Stake"
    }
   ]
  },
  {
   "title": "Balance on Vote Account",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "targets": [
    {
     "expr": "nodemonitor_validatorVoteBalance{pubkey=\"$pubkey\"}",
     "legendFormat": "Balance Vote Account"
    }
   ]
  },
  { "title": "SFDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Onboarding priority",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nodemonitor_sfdp_onboarding_number{pubkey=\"$pubkey\"}",
     "legendFormat": "Stake"
    }
   ]
  },
  {
   "title": "Score",
   "type": "stat",
   "description": "Based on top validator performance",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodemonitor_validatorScore{chain_net=\"testnet\", instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Onboarding in mainnet",
   "type": "stat",
   "description": "Estimation for onboarding in mainnet",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nodemonitor_sfdp_onboarding_number{pubkey=\"$pubkey\"}) / (((nodemonitor_sfdp_onboarding_number{pubkey=\"$pubkey\"} offset 14d) - nodemonitor_sfdp_onboarding_number{pubkey=\"$pubkey\"})/14) * 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Stats $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 }, "repeat": "node" },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Load Averages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "short"
    },
    {
     "expr": "node_load5{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "medium"
    },
    {
     "expr": "node_load15{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "long"
    }
   ]
  },
  {
   "title": "Swap usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "used",
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "used",
     "measurement": "swap",
     "query": "select mean(used) as used from \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "used" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "total",
     "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "total",
     "measurement": "swap",
     "query": "select mean(total) as total from \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "total" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Buffer"
    }
   ]
  },
  {
   "title": "Netstat IP In / Out Octets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InOctets{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "InOctets - Received octets"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutOctets{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "OutOctets - Sent octets"
    }
   ]
  },
  {
   "title": "UDP datagrams",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "in datagrams",
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "function": "derivative",
     "groupBy": " by (host)",
     "legendFormat": "InDatagrams - Datagrams received",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(udp_indatagrams), 1s) as \"in datagrams\" FROM \"net\" WHERE host =~ /$server/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "udp_indatagrams" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "out datagrams",
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "function": "derivative",
     "groupBy": " by (host)",
     "legendFormat": "OutDatagrams - Datagrams sent",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(udp_outdatagrams), 1s) as \"out datagrams\" FROM \"net\" WHERE host =~ /$server/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "udp_outdatagrams" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server\"}"
    }
   ]
  },
  {
   "title": "UDP errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "checksum errors",
     "expr": "irate(node_netstat_UdpLite_InErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "NoPorts - UDP Datagrams received on a port with no listener",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpInCsumErrors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "no ports",
     "expr": "irate(node_netstat_Udp_NoPorts{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "NoPorts - UDP Datagrams received on a port with no listener",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpNoPorts" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "no ports",
     "expr": "irate(node_netstat_Udp_RcvbufErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "RcvbufErrors - UDP buffer errors received",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpNoPorts" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "in errors",
     "expr": "irate(node_netstat_Udp_InErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "InErrors - UDP Datagrams that could not be delivered to an application",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpInErrors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "no ports",
     "expr": "irate(node_netstat_Udp_SndbufErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "SndbufErrors - UDP buffer errors send",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpNoPorts" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "TCP connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "CLOSED",
     "expr": "irate(node_netstat_Tcp_InSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "function": "derivative",
     "groupBy": " by (host)",
     "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections",
     "measurement": "netstat",
     "query": "select mean(tcp_close) as CLOSED from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "tcp_close" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "CLOSE_WAIT",
     "expr": "irate(node_netstat_Tcp_OutSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "function": "derivative",
     "groupBy": " by (host)",
     "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets",
     "measurement": "netstat",
     "query": "select mean(tcp_close_wait) as CLOSE_WAIT from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "tcp_close_wait" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "TCP Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "checksum errors",
     "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpInCsumErrors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "no ports",
     "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpNoPorts" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "no ports",
     "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpNoPorts" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "in errors",
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpInErrors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "no ports",
     "expr": "irate(node_netstat_Tcp_InErrs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpNoPorts" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "no ports",
     "expr": "irate(node_netstat_Tcp_OutRsts{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "OutRsts - Segments sent with RST flag",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpNoPorts" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "IOWait"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "running",
     "expr": "node_procs_blocked{instance=\"$node\",job=\"$job\"}",
     "groupBy": " by (host)",
     "legendFormat": "Processes blocked waiting for I/O to complete",
     "measurement": "processes",
     "query": "select mean(running) as running from \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "running" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "blocked",
     "expr": "node_procs_running{instance=\"$node\",job=\"$job\"}",
     "groupBy": " by (host)",
     "legendFormat": "Processes in runnable state",
     "measurement": "processes",
     "query": "select mean(blocked) as blocked from \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "blocked" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_max_fds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Maximum open file descriptors"
    },
    {
     "expr": "process_open_fds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Context Switches / Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "expr": "irate(node_context_switches_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "groupBy": " by (host)",
     "legendFormat": "Context switches",
     "measurement": "kernel",
     "query": "SELECT non_negative_derivative(mean(context_switches),1s)as \"context switches\"  FROM \"kernel\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "context_switches" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "expr": "irate(node_intr_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "groupBy": " by (host)",
     "legendFormat": "Interrupts",
     "measurement": "kernel",
     "query": "SELECT non_negative_derivative(mean(context_switches),1s)as \"context switches\"  FROM \"kernel\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "context_switches" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  }
 ]
}